const { requireAuth } = require("../middleware/authMiddleware");
const express = require("express");
const authController = require("../controllers/authController");
const router = express.Router();
router.post("/register", authController.register);
router.post("/login", authController.login);
router.post("/logout", authController.logout);
router.post("/guest", authController.guest);
router.post("/forgot-password", authController.forgotPassword);
router.post("/reset-password", authController.resetPassword);
router.get("/cas/login", authController.casLogin);
router.get("/me", authController.me);
module.exports = router;
